src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommandeRepository::class)
 */
class Commande
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="commandes")
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=Achat::class, mappedBy="commande")
     */
    private $achats;

    /**
     * @ORM\Column(type="integer")
     */
    private $montant_total;

    /**
     * @return mixed
     */
    public function getMontantTotal()
    {
        return $this->montant_total;
    }

    /**
     * @param mixed $montant_total
     */
    public function setMontantTotal($montant_total): void
    {
        $this->montant_total = $montant_total;
    }

    public function __construct()
    {
        $this->achats = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Achat[]
     */
    public function getAchats(): Collection
    {
        return $this->achats;
    }

    public function addAchat(Achat $achat): self
    {
        if (!$this->achats->contains($achat)) {
            $this->achats[] = $achat;
            $achat->setCommande($this);
        }

        return $this;
    }

    public function removeAchat(Achat $achat): self
    {
        if ($this->achats->removeElement($achat)) {
            // set the owning side to null (unless already changed)
            if ($achat->getCommande() === $this) {
                $achat->setCommande(null);
            }
        }

        return $this;
    }


}

src/Controller/FrontController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;
use App\Repository\CategorieRepository;
use App\Repository\CommandeRepository;
use App\Service\Panier\PanierService;
use Knp\Component\Pager\PaginatorInterface;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class FrontController extends AbstractController
{
    // cette fonction affiche la page d'accueil, d'où sa route configurée sur "/".
    // Toute fonction possédant un return necessite une route en paramètre (géree par Annotion\Route)
    //ainsi qu'un name qui permettra d'appeler cette fonction dans notre twig
    /**
     * @Route ("/", name="home")
     */
    public function home(ArticleRepository $articleRepository,CategorieRepository $categorieRepository,PanierService $panierService, PaginatorInterface $paginator, Request $request) //ici on injecte la dépendance de ArticleRepository afin de pouvoir utiliser les méthode de la classe ArticleRepository
    {

//        $prenom="cesaire";
//        $nom="desaulle";
//        $age=34;
        $panier=$panierService->getFullPanier();
        $categories=$categorieRepository->findAll();


        $articles=$articleRepository->findAll();// on utilise la méthode findAll de ArticleRepository afin de faire une requête de select * de nos articles que nous allons transmettre à notre vue twig
        $articles=$paginator->paginate(
            $articles,
            $request->query->getInt('page', 1),
            6

        );


        return $this->render('front/home.html.twig',[
//            'prenom'=>$prenom,
//            'nom'=>$nom,
//            'age'=>$age,
            'articles'=>$articles,
            'panier'=>$panier,
            'categories'=>$categories

        ]);
    }

    /**
     * @Route ("/homefilter",name="homefilter")
     */
    public function homefilter(ArticleRepository $articleRepository, CategorieRepository $categorieRepository,PanierService $panierService, Request $request, PaginatorInterface $paginator)
    {

        $panier=$panierService->getFullPanier();
        $categories=$categorieRepository->findAll();

        $prixmax=$request->request->get('prixmax');
        $cat=$request->request->get('cat');

        if ($cat=='all' && $prixmax==50):
            $articles=$articleRepository->findAll();
        elseif($cat!=='all' && $prixmax==50):
            $articles=$articleRepository->findBy(['categorie'=>$cat],['prix'=>'ASC']);
        elseif ($cat=='all' && $prixmax!==50):
            $articles=$articleRepository->findByPrice($prixmax);
        elseif ($cat!=='all' && $prixmax!==50):
            $articles=$articleRepository->findByCategoryAndPrice($cat, $prixmax);
        endif;
        $articles=$paginator->paginate(
            $articles,
            $request->query->getInt('page', 1),
            6

        );
        return $this->render('front/home.html.twig',[
            'articles'=>$articles,
            'panier'=>$panier,
            'categories'=>$categories
        ]);
    }

    /**
     * @Route ("/commandes_user",name="commandes_user")
     */
    public function commandes_user(CommandeRepository $repository)
    {
        $commandes=$repository->findBy(['user'=>$this->getUser()], ['id'=>'DESC']);

        return $this->render("front/commandes_user.html.twig",[
            'commandes'=>$commandes
        ]);

    }

    /**
     * @Route("/mail_form", name="mail_form")
     */
    public function mail_form()
    {
        return $this->render("front/mail_form.html.twig");
}

























}

templates/front/commandes_user.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        {% for commande in commandes %}
            <table class="table">
                <thead class="thead-primary text-center">
                <tr>
                    <th colspan="6">Commande N°{{ commande.id }} d'un montant total de {{ commande.montantTotal }}€ éffectuée le {{ commande.date | date('d/m/Y') }}</th>
                </tr>
                <tr>
                    <th >Nom</th>
                    <th >Ref</th>
                    <th >Photo</th>
                    <th >Quantité</th>
                    <th >Prix Total</th>
                    <th >Action</th>
                </tr>
                </thead>
                <tbody class="text-center">



                {% for item in commande.achats %}
                    <tr>
                        <td>{{  item.article.nom }}</td>
                        <td>{{ item.article.ref }}</td>
                        <td><img height="40" width="40" src="{{ asset('Photos/') }}{{ item.article.photo }}" alt="{{ item.article.nom }}"></td>

                        <td>{{  item.quantite }}</td>
                        <td>{{ item.article.prix * item.quantite }}</td>

                        <td>
                            <a href=""><button class="btn btn-outline-danger btn-rounded" >Annuler</button></a></td>
                    </tr>
                {% endfor %}

                </tbody>

            </table>
        {% endfor %}

    </div>

{% endblock %}

templates/front/home.html.twig
{% extends 'base.html.twig' %}
{% block title %}
    {{ parent() }}Accueil
{% endblock %}
{% block titre %}
    Bienvenue !!
{% endblock %}



{% block body %}
    {# Bonjour {{ prenom }}, {{ nom }}, {{ age }} ans. <br> #}
    {# Nous sommes le {{ "now" | date("d/m/Y") }}, il est {{ "now" | date("H:i:s") }} #}





    {% for message in app.flashes('success') %}
        <div class="row mt-4">
            <div class="alert alert-success col-md-6 text-center">
                {{ message }}
            </div>
        </div>
    {% endfor %}

    <div class="row justify-content-between ms-3 mt-4">
        <div class="col-md-2">
            {% if panier is not empty %}
                <div style="font-size: 0.5rem;" class="me-3 text-center">
                    <a class="btn btn-primary" href="{{ path('cart') }}">Accéder à mon panier<i  class="fas fa-cart-arrow-down fa-sm"></i></a>
                </div>
            {% endif %}
            <div class="list-group mb-4">

                <form action="{{ path('homefilter') }}" method="post">
                    <div class="form-group">
                        <label for="exampleSelect1" class="form-label mt-4">Catégories</label>
                        <select class="form-select" name="cat" id="exampleSelect1">
                            <option value="all">Tous nos bijoux</option>
                            {% for categorie in categories %}
                                <option value="{{ categorie.id }}">{{ categorie.nom }} </option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="pt-4">
                        <label for="">Votre budget</label>
                        <div class="range-wrap mt-4 ms-3 ">
                            <div class="range-value" id="rangeV"></div>
                            <input id="range" name="prixmax" type="range" min="50" max="1500" value="0" step="50">
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary mt-2">Filtrer</button>
                </form>


            </div>
        </div>
        <div class="col-md-9">
            <div class="row justify-content-between">
                {% for article in articles %}
                    <div class="col-md-4">
                        <div style="width: 15rem" class="card mb-5">

                            <img src="{{ asset('Photos/') }}{{ article.photo }}" height="200" alt="">

                            <div class="card-body p-1 text-center">
                                <h5 class="card-title">{{ article.nom }}</h5>
                            </div>
                            <div class="card-body p-0">
                                <p class="card-text">{{ article.description }}</p>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">{{ article.prix }} €</li>
                                <a href="{{ path('addcart', {id:article.id,param:'home'}) }}">
                                    <button type="button" class="btn btn-primary btn-sm w-100">
                                        <i class="fas fa-shopping-cart fa-lg"></i>
                                    </button>
                                </a>
                            </ul>
                        </div>

                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="row justify-content-center mb-5">
            <div class="pagination-small ps-5 col-md-4 text-center">
                {{ knp_pagination_render(articles) }}
            </div>
        </div>
    </div>



    <script>
        const
            range = document.getElementById('range'),
            rangeV = document.getElementById('rangeV'),
            setValue = () => {
                const
                    newValue = Number((range.value - range.min) * 100 / (range.max - range.min)),
                    newPosition = 10 - (newValue * 0.2);
                rangeV.innerHTML = `<span>${range.value}</span>`;
                rangeV.style.left = `calc(${newValue}% + (${newPosition}px))`;

            };
        document.addEventListener("DOMContentLoaded", setValue);
        range.addEventListener('input', setValue);

    </script>

{% endblock %}

templates/front/mail_form.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
    <h1>Formulaire de contact</h1>
    <form id="contact-form" method="post" action="{{ path('send_mail') }}" role="form">


        <div class="messages"></div>

        <div class="controls">

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="form_name">Prénom *</label>
                        <input id="form_name" type="text" name="name" class="form-control" placeholder="Veuillez saisir votre prénom *" required="required" data-error="Firstname is required.">
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="form_lastname">Nom *</label>
                        <input id="form_lastname" type="text" name="surname" class="form-control" placeholder="Veuillez saisir votre nom *" required="required" data-error="Lastname is required.">
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="form_email">Email *</label>
                        <input id="form_email" type="email" name="email" class="form-control" placeholder="Veuillez saisir votre email *" required="required" data-error="Valid email is required.">
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="form_need">Spécifiez l'objet de votre mail *</label>
                        <select id="form_need" name="need" class="form-control" required="required" data-error="Spécifiez l'objet de votre mail">
                            <option value=""></option>
                            <option value="Reclamation">Réclamation</option>
                            <option value="Informations">Informations</option>
                            <option value="Autre">Autre</option>
                        </select>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="form_message">Message *</label>
                        <textarea id="form_message" name="message" class="form-control" placeholder="Message *" rows="4" required="required" data-error="Please, leave us a message."></textarea>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <div class="col-md-12 mt-4">
                    <input type="submit" class="btn btn-success btn-send" value="Envoyer">
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <p class="text-muted">
                        <strong>*</strong> Ces champs sont requis
                </div>
            </div>
        </div>

    </form>
    </div>
{% endblock %}

templates/front/mail_template.html.twig
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:v="urn:schemas-microsoft-com:vml"
      xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
    <!--[if gte mso 9]><xml>
        <o:OfficeDocumentSettings>
            <o:AllowPNG/>
            <o:PixelsPerInch>96</o:PixelsPerInch>
        </o:OfficeDocumentSettings>
    </xml><![endif]-->
    <!-- fix outlook zooming on 120 DPI windows devices -->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- So that mobile will display zoomed in -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge"> <!-- enable media queries for windows phone 8 -->
    <meta name="format-detection" content="date=no"> <!-- disable auto date linking in iOS 7-9 -->
    <meta name="format-detection" content="telephone=no"> <!-- disable auto telephone linking in iOS 7-9 -->
    <title>Single Column</title>

    <style type="text/css">
        body {
            margin: 0;
            padding: 0;
            -ms-text-size-adjust: 100%;
            -webkit-text-size-adjust: 100%;
        }

        table {
            border-spacing: 0;
        }

        table td {
            border-collapse: collapse;
        }

        .ExternalClass {
            width: 100%;
        }

        .ExternalClass,
        .ExternalClass p,
        .ExternalClass span,
        .ExternalClass font,
        .ExternalClass td,
        .ExternalClass div {
            line-height: 100%;
        }

        .ReadMsgBody {
            width: 100%;
            background-color: #ebebeb;
        }

        table {
            mso-table-lspace: 0pt;
            mso-table-rspace: 0pt;
        }

        img {
            -ms-interpolation-mode: bicubic;
        }

        .yshortcuts a {
            border-bottom: none !important;
        }

        @media screen and (max-width: 599px) {
            .force-row,
            .container {
                width: 100% !important;
                max-width: 100% !important;
            }
        }
        @media screen and (max-width: 400px) {
            .container-padding {
                padding-left: 12px !important;
                padding-right: 12px !important;
            }
        }
        .ios-footer a {
            color: #aaaaaa !important;
            text-decoration: underline;
        }
        a[href^="x-apple-data-detectors:"],
        a[x-apple-data-detectors] {
            color: inherit !important;
            text-decoration: none !important;
            font-size: inherit !important;
            font-family: inherit !important;
            font-weight: inherit !important;
            line-height: inherit !important;
        }
    </style>
</head>

<body style="margin:0; padding:0;" bgcolor="#F0F0F0" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">

<!-- 100% background wrapper (grey background) -->
<table border="0" width="100%" height="100%" cellpadding="0" cellspacing="0" bgcolor="#F0F0F0">
    <tr>
        <td align="center" valign="top" bgcolor="#F0F0F0" style="background-color: #F0F0F0;">

            <br>
            <img src="{{ cid }}" alt="">

            <!-- 600px container (white background) -->
            <table  border="0" width="600" cellpadding="0" cellspacing="0" class="container" style="width:600px;max-width:600px">
                <tr>
                    <td class="container-padding header" align="left" style="font-family:Helvetica, Arial, sans-serif;font-size:24px;font-weight:bold;padding-bottom:12px;color:#DF4726;padding-left:24px;padding-right:24px">
                        {{ motif }}
                    </td>
                </tr>
                <tr>
                    <td class="container-padding content" align="left" style="padding-left:24px;padding-right:24px;padding-top:12px;padding-bottom:12px;background-color:#ffffff">
                        <br>

                        <div class="title" style="font-family:Helvetica, Arial, sans-serif;font-size:18px;font-weight:600;color:#374550">
                            {{ nom }} {{ prenom }} {{ email }}</div>
                        <br>

                        <div class="body-text" style="font-family:Helvetica, Arial, sans-serif;font-size:14px;line-height:20px;text-align:left;color:#333333">
                            {{ message }}
                            <br><br>
                        </div>

                    </td>
                </tr>
            </table>

            <br><br>

        </td>
    </tr>
    <br><br>
</table>
<br>
<br>


</body>
</html>

templates/front/panier.html.twig
{% extends 'base.html.twig' %}
{% block title %}
    {{ parent() }}Panier
{% endblock %}
 {% block titre %}
     Panier
 {% endblock %}
{% block body %}

    <div class="container">

        {% for message in app.flashes('success') %}
            <div class="row mt-4">
                <div class="alert alert-success col-md-6 text-center">
                    {{ message }}
                </div>
            </div>
        {% endfor %}
        {% for message in app.flashes('alert') %}
            <div class="row mt-4">
                <div class="alert alert-danger col-md-6 text-center">
                    {{ message }}
                </div>
            </div>
        {% endfor %}

        {% if panier is not empty %}

            <table class="table">
                <thead class="thead-dark text-center">
                <tr>
                    <th >Nom</th>
                    <th >Ref</th>
                    <th >Photo</th>
                    <th >Prix Total</th>
                    <th ><button class="btn btn-primary">Retirer</button></th>
                    <th >Quantité</th>
                    <th ><button class="btn btn-primary">Ajouter</button>  </th>
                    <th >Annuler</th>
                </tr>
                </thead>
                <tbody class="text-center">



                {% for item in panier %}
                    <tr>
                        <td>{{  item.article.nom }}</td>
                        <td>{{ item.article.ref }}</td>
                        <td><img height="40" width="40" src="{{ asset('Photos/') }}{{ item.article.photo }}" alt="{{ item.article.nom }}"></td>

                        <td>{{ item.article.prix * item.quantite }}</td>
                        <td>
                            <a href="{{ path('removecart', {'id': item.article.id}) }}"><button class="btn btn-primary text-white">-</button></a></td>
                        <td>{{ item.quantite }}</td>
                        <td>
                            <a href="{{ path('addcart', {'id': item.article.id,'param':"panier"}) }}"><button class="btn btn-primary text-white">+</button></a></td>

                        <td>
                            <a href="{{ path('deletecart', {'id': item.article.id}) }}"><button class="btn btn-outline-danger btn-rounded" >Annuler</button></a></td>
                    </tr>
                {% endfor %}

                </tbody>

            </table>
            <form action="{{ path('verif_promo') }}" method="post" >
                <div class="form-group">
                    <label for="">Vous avez un code promo?</label>
                    <input class="form-control" name="promo" type="text" placeholder="Veuillez saisir votre code promo">
                </div>
                <button class="btn btn-primary mt-2" type="submit">Vérifier la validité</button>
            </form>
            {% if totalremise is defined %}

                <div class="col-md-8 mt-2"><h4>Total de la commande avant remise : <span style="text-decoration: line-through">{{ total }} €</span></h4></div>
                <div class="col-md-8 mt-2"><h4>Montant total après remise : {{ totalremise }} €</h4></div>
            {% else %}
                <div class="col-md-8 mt-2"><h4>Total de la commande : {{ total }} €</h4></div>
            {% endif %}
            {% if app.user %}

                {% if totalremise is defined %}

                    <div class="col-md-4 mb-5 mt-2"><a href="{{ path('commande',{'param':'remise' }) }}">
                            <button class="btn btn-success">Commander</button>
                        </a>
                    </div>
                {% else %}
                    <div class="col-md-4 mb-5 mt-2"><a href="{{ path('commande') }}">
                            <button class="btn btn-success">Commander</button>
                        </a>
                    </div>

                {% endif %}

            {% else %}
                <div class="col-md-4 mb-5"><a href="{{ path('login') }}">
                        <button class="btn btn-success">Connectez-vous pour passer à la commande</button>
                    </a>
                </div>

            {% endif %}
        {% else %}
            <h3>Votre Panier est vide, allez vite le remplir <a class="hover" href="{{ path('home') }}">Nos Bijoux</a></h3>
        {% endif %}
    </div>

{% endblock %}